#!/bin/bash

# Create VirtualBox VM using an Ubuntu server ISO
# https://www.linuxtechi.com/manage-virtualbox-virtual-machines-command-line/

PROJ_DIR="$(pwd)"
ISO_PATH="$PROJ_DIR/iso"     
VM_NAME="reversing-framework"
OS_TYPE="Ubuntu_64"
VBOX_PATH="$PROJ_DIR/$VM_NAME/$VM_NAME.vdi"
 
# Check if iso exists already, otherwise download it
# This should be replaced with a python script in future for given user file     
ISO_FILE="$(find $ISO_PATH -type f -name '*.iso')"
if [ -z $ISO_FILE ]; then     
    echo "No ISO found, downloading ubuntu-18.04.2 server image"     
    wget -P $ISO_PATH "http://cdimage.ubuntu.com/releases/18.04/release/ubuntu-18.04.2-server-amd64.iso"    
    ISO_FILE="ubuntu-18.04.2-server-amd64.iso"     
    echo "using ISO $(basename $ISO_FILE)"     
else
    echo "Found ISO $(basename $ISO_FILE)"
fi


# VBox create VM
VBoxManage createvm --name $VM_NAME --ostype $OS_TYPE --register
# need to create network here
VBoxManage modifyvm $VM_NAME --memory 1024
VBoxManage createhd --filename $VBOX_PATH --size 10000 --format VDI
VBoxManage storagectl $VM_NAME --name "SATA Controller" --add sata --controller IntelAhci
VBoxManage storageattach $VM_NAME --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium $VBOX_PATH
VBoxManage storagectl $VM_NAME --name "IDE Controller" --add ide --controller PIIX4
VBoxManage storageattach $VM_NAME --storagectl "IDE Controller" --port 1 --device 0 --type dvddrive --medium $ISO_FILE

# Start VM
VBoxManage startvm $VM_NAME
